### ISSUE TITLE
Include usage instructions

### ISSUE THREAD

**Issue by trosel** [Jaruzel/DeleteFacebookActivity#1]
executable link here: https://github.com/Jaruzel/DeleteFacebookActivity/blob/master/DeleteFacebookActivity/bin/Release/DeleteFacebookActivity.exe?raw=true

Found on the blog post here: http://www.jaruzel.com/blog/how-i-erased-5000-facebook-comments-and-likes

If people want to build from source, I guess they download the repo and import it into Visual Studio?

**Comment by Jaruzel** [comment]
Yes, that should work.  I've updated the readme now - thanks!
